# Generated by Django 3.0.4 on 2020-07-10 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('amount', models.FloatField(default=0)),
                ('tran_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
