# Generated by Django 3.0.4 on 2020-07-02 04:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('desc', models.TextField(default='')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 7, 2, 4, 53, 57, 623304, tzinfo=utc))),
            ],
        ),
    ]
