# Generated by Django 3.0.4 on 2020-07-02 04:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 4, 57, 14, 191081, tzinfo=utc)),
        ),
    ]
