# Generated by Django 3.0.4 on 2020-07-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200702_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('content', models.TextField(default='')),
                ('author', models.CharField(default='', max_length=50)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
